<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ColorsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Disable foreign key checks
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        
        // Clear existing data
        DB::table('colors')->truncate();
        
        // Insert new data
        DB::table('colors')->insert([
            [
                'id' => 314,
                'color_name' => 'AREOLY',
                'color_description' => 'Arenito/Olympian',
                'color_code' => 'AREOLY',
                'product_id' => 27,
                'collection_id' => 11,
                'flag_product_id' => 1,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-10 17:59:44',
                'updated_at' => '2025-09-10 18:00:47',
                'deleted_at' => '2025-09-10 18:00:47',
            ],
            [
                'id' => 315,
                'color_name' => 'ARESOL',
                'color_description' => 'Arenito/Solar',
                'color_code' => 'ARESOL',
                'product_id' => 27,
                'collection_id' => 11,
                'flag_product_id' => 1,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-10 17:59:44',
                'updated_at' => '2025-09-10 18:00:47',
                'deleted_at' => '2025-09-10 18:00:47',
            ],
            [
                'id' => 316,
                'color_name' => 'RYLVRD',
                'color_description' => 'Royal/Verde',
                'color_code' => 'RYLVRD',
                'product_id' => 27,
                'collection_id' => 11,
                'flag_product_id' => 1,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-10 17:59:44',
                'updated_at' => '2025-09-10 18:00:47',
                'deleted_at' => '2025-09-10 18:00:47',
            ],
            [
                'id' => 317,
                'color_name' => 'AREOLY',
                'color_description' => 'Arenito/Olympian',
                'color_code' => 'AREOLY',
                'product_id' => 27,
                'collection_id' => 11,
                'flag_product_id' => 1,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-10 18:00:47',
                'updated_at' => '2025-09-10 18:10:44',
                'deleted_at' => '2025-09-10 18:10:44',
            ],
            [
                'id' => 318,
                'color_name' => 'ARESOL',
                'color_description' => 'Arenito/Solar',
                'color_code' => 'ARESOL',
                'product_id' => 27,
                'collection_id' => 11,
                'flag_product_id' => 1,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-10 18:00:47',
                'updated_at' => '2025-09-10 18:10:44',
                'deleted_at' => '2025-09-10 18:10:44',
            ],
            [
                'id' => 319,
                'color_name' => 'RYLVRD',
                'color_description' => 'Royal/Verde',
                'color_code' => 'RYLVRD',
                'product_id' => 27,
                'collection_id' => 11,
                'flag_product_id' => 1,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-10 18:00:47',
                'updated_at' => '2025-09-10 18:10:44',
                'deleted_at' => '2025-09-10 18:10:44',
            ],
            [
                'id' => 320,
                'color_name' => 'AREOLY',
                'color_description' => 'Arenito/Olympian',
                'color_code' => 'AREOLY',
                'product_id' => 27,
                'collection_id' => 11,
                'flag_product_id' => 1,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-10 18:10:44',
                'updated_at' => '2025-09-10 20:17:53',
                'deleted_at' => '2025-09-10 20:17:53',
            ],
            [
                'id' => 321,
                'color_name' => 'ARESOL',
                'color_description' => 'Arenito/Solar',
                'color_code' => 'ARESOL',
                'product_id' => 27,
                'collection_id' => 11,
                'flag_product_id' => 1,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-10 18:10:44',
                'updated_at' => '2025-09-10 20:17:53',
                'deleted_at' => '2025-09-10 20:17:53',
            ],
            [
                'id' => 322,
                'color_name' => 'RYLVRD',
                'color_description' => 'Royal/Verde',
                'color_code' => 'RYLVRD',
                'product_id' => 27,
                'collection_id' => 11,
                'flag_product_id' => 1,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-10 18:10:44',
                'updated_at' => '2025-09-10 20:17:53',
                'deleted_at' => '2025-09-10 20:17:53',
            ],
            [
                'id' => 323,
                'color_name' => 'Branco/Olympian',
                'color_description' => 'Branco/Olympian',
                'color_code' => 'BCOOLY',
                'product_id' => 28,
                'collection_id' => 11,
                'flag_product_id' => 1,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-10 18:22:05',
                'updated_at' => '2025-09-10 18:22:05',
                'deleted_at' => null,
            ],
            [
                'id' => 324,
                'color_name' => 'Arenito/Multi',
                'color_description' => 'Arenito/Multi',
                'color_code' => 'ARENML',
                'product_id' => 28,
                'collection_id' => 11,
                'flag_product_id' => 1,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-10 18:22:05',
                'updated_at' => '2025-09-10 18:22:05',
                'deleted_at' => null,
            ],
            [
                'id' => 325,
                'color_name' => 'Preto/Chumbo',
                'color_description' => 'Preto/Chumbo',
                'color_code' => 'PTO/CH',
                'product_id' => 28,
                'collection_id' => 11,
                'flag_product_id' => 1,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-10 18:22:05',
                'updated_at' => '2025-09-10 18:22:05',
                'deleted_at' => null,
            ],
            [
                'id' => 326,
                'color_name' => 'Mist',
                'color_description' => 'Mist',
                'color_code' => 'MIST',
                'product_id' => 28,
                'collection_id' => 11,
                'flag_product_id' => 1,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-10 18:22:05',
                'updated_at' => '2025-09-10 18:22:05',
                'deleted_at' => null,
            ],
            [
                'id' => 327,
                'color_name' => 'Petroleo/Solar',
                'color_description' => 'Petroleo/Solar',
                'color_code' => 'PTLSLR',
                'product_id' => 28,
                'collection_id' => 11,
                'flag_product_id' => 1,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-10 18:22:05',
                'updated_at' => '2025-09-10 18:22:05',
                'deleted_at' => null,
            ],
            [
                'id' => 328,
                'color_name' => 'Chumbo/Arenito',
                'color_description' => 'Chumbo/Arenito',
                'color_code' => 'CHBARE',
                'product_id' => 29,
                'collection_id' => 11,
                'flag_product_id' => 1,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-10 18:28:45',
                'updated_at' => '2025-09-10 20:16:59',
                'deleted_at' => '2025-09-10 20:16:59',
            ],
            [
                'id' => 329,
                'color_name' => 'Arenito/Olympian',
                'color_description' => 'Arenito/Olympian',
                'color_code' => 'AREOLY',
                'product_id' => 29,
                'collection_id' => 11,
                'flag_product_id' => 1,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-10 18:28:45',
                'updated_at' => '2025-09-10 20:16:59',
                'deleted_at' => '2025-09-10 20:16:59',
            ],
            [
                'id' => 330,
                'color_name' => 'Preto/Chumbo',
                'color_description' => 'Preto/Chumbo',
                'color_code' => 'PTO/CH',
                'product_id' => 30,
                'collection_id' => 11,
                'flag_product_id' => 1,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-10 20:02:38',
                'updated_at' => '2025-09-10 20:03:27',
                'deleted_at' => '2025-09-10 20:03:27',
            ],
            [
                'id' => 331,
                'color_name' => 'Militar/Preto',
                'color_description' => 'Militar/Preto',
                'color_code' => 'MLT/PT',
                'product_id' => 30,
                'collection_id' => 11,
                'flag_product_id' => 1,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-10 20:02:38',
                'updated_at' => '2025-09-10 20:03:27',
                'deleted_at' => '2025-09-10 20:03:27',
            ],
            [
                'id' => 332,
                'color_name' => 'Branco/Preto',
                'color_description' => 'Branco/Preto',
                'color_code' => 'BCOPTO',
                'product_id' => 30,
                'collection_id' => 11,
                'flag_product_id' => 1,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-10 20:02:38',
                'updated_at' => '2025-09-10 20:03:27',
                'deleted_at' => '2025-09-10 20:03:27',
            ],
            [
                'id' => 333,
                'color_name' => 'Arenito/Lilas',
                'color_description' => 'Arenito/Lilas',
                'color_code' => 'ARELLS',
                'product_id' => 30,
                'collection_id' => 11,
                'flag_product_id' => 1,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-10 20:02:38',
                'updated_at' => '2025-09-10 20:03:27',
                'deleted_at' => '2025-09-10 20:03:27',
            ],
            [
                'id' => 334,
                'color_name' => 'Preto/Chumbo',
                'color_description' => 'Preto/Chumbo',
                'color_code' => 'PTO/CH',
                'product_id' => 30,
                'collection_id' => 11,
                'flag_product_id' => 1,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-10 20:03:27',
                'updated_at' => '2025-09-18 16:29:33',
                'deleted_at' => '2025-09-18 16:29:33',
            ],
            [
                'id' => 335,
                'color_name' => 'Militar/Preto',
                'color_description' => 'Militar/Preto',
                'color_code' => 'MLT/PT',
                'product_id' => 30,
                'collection_id' => 11,
                'flag_product_id' => 1,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-10 20:03:27',
                'updated_at' => '2025-09-18 16:29:33',
                'deleted_at' => '2025-09-18 16:29:33',
            ],
            [
                'id' => 336,
                'color_name' => 'Branco/Preto',
                'color_description' => 'Branco/Preto',
                'color_code' => 'BCOPTO',
                'product_id' => 30,
                'collection_id' => 11,
                'flag_product_id' => 1,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-10 20:03:27',
                'updated_at' => '2025-09-18 16:29:33',
                'deleted_at' => '2025-09-18 16:29:33',
            ],
            [
                'id' => 337,
                'color_name' => 'Arenito/Lilas',
                'color_description' => 'Arenito/Lilas',
                'color_code' => 'ARELLS',
                'product_id' => 30,
                'collection_id' => 11,
                'flag_product_id' => 1,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-10 20:03:27',
                'updated_at' => '2025-09-18 16:29:33',
                'deleted_at' => '2025-09-18 16:29:33',
            ],
            [
                'id' => 338,
                'color_name' => 'Chumbo/Preto',
                'color_description' => 'Chumbo/Preto',
                'color_code' => 'CHB/PT',
                'product_id' => 31,
                'collection_id' => 11,
                'flag_product_id' => 3,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-10 20:09:27',
                'updated_at' => '2025-09-15 20:36:43',
                'deleted_at' => '2025-09-15 20:36:43',
            ],
            [
                'id' => 339,
                'color_name' => 'Elderme/Ameixa',
                'color_description' => 'Elderme/Ameixa',
                'color_code' => 'ELDAME',
                'product_id' => 31,
                'collection_id' => 11,
                'flag_product_id' => 3,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-10 20:09:27',
                'updated_at' => '2025-09-10 20:30:39',
                'deleted_at' => '2025-09-10 20:30:39',
            ],
            [
                'id' => 340,
                'color_name' => 'Preto/Preto',
                'color_description' => 'Preto/Preto',
                'color_code' => 'PTO/PT',
                'product_id' => 31,
                'collection_id' => 11,
                'flag_product_id' => 3,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-10 20:09:27',
                'updated_at' => '2025-09-10 20:30:39',
                'deleted_at' => '2025-09-10 20:30:39',
            ],
            [
                'id' => 341,
                'color_name' => 'Algodão/Dusty',
                'color_description' => 'Algodão/Dusty',
                'color_code' => 'ALGDST',
                'product_id' => 31,
                'collection_id' => 11,
                'flag_product_id' => 3,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-10 20:09:27',
                'updated_at' => '2025-09-10 20:30:39',
                'deleted_at' => '2025-09-10 20:30:39',
            ],
            [
                'id' => 342,
                'color_name' => 'Cinza/Steel',
                'color_description' => 'Cinza/Steel',
                'color_code' => 'CZASTE',
                'product_id' => 31,
                'collection_id' => 11,
                'flag_product_id' => 3,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-10 20:09:27',
                'updated_at' => '2025-09-10 20:30:39',
                'deleted_at' => '2025-09-10 20:30:39',
            ],
            [
                'id' => 343,
                'color_name' => 'Arenito/Marfim',
                'color_description' => 'Arenito/Marfim',
                'color_code' => 'ARTMRF',
                'product_id' => 31,
                'collection_id' => 11,
                'flag_product_id' => 3,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-10 20:09:27',
                'updated_at' => '2025-09-10 20:30:39',
                'deleted_at' => '2025-09-10 20:30:39',
            ],
            [
                'id' => 344,
                'color_name' => 'Chumbo/Verde',
                'color_description' => 'Chumbo/Verde',
                'color_code' => 'CHB/VD',
                'product_id' => 32,
                'collection_id' => 11,
                'flag_product_id' => 1,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-10 20:15:23',
                'updated_at' => '2025-09-10 20:30:46',
                'deleted_at' => '2025-09-10 20:30:46',
            ],
            [
                'id' => 345,
                'color_name' => 'Preto/Preto',
                'color_description' => 'Preto/Preto',
                'color_code' => 'PTO/PT',
                'product_id' => 32,
                'collection_id' => 11,
                'flag_product_id' => 1,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-10 20:15:23',
                'updated_at' => '2025-09-10 20:30:46',
                'deleted_at' => '2025-09-10 20:30:46',
            ],
            [
                'id' => 346,
                'color_name' => 'Marinho/Dourado',
                'color_description' => 'Marinho/Dourado',
                'color_code' => 'MRHDRD',
                'product_id' => 32,
                'collection_id' => 11,
                'flag_product_id' => 1,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-10 20:15:23',
                'updated_at' => '2025-09-10 20:30:46',
                'deleted_at' => '2025-09-10 20:30:46',
            ],
            [
                'id' => 347,
                'color_name' => 'Arenito/Chumbo',
                'color_description' => 'Arenito/Chumbo',
                'color_code' => 'ARECHB',
                'product_id' => 32,
                'collection_id' => 11,
                'flag_product_id' => 1,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-10 20:15:23',
                'updated_at' => '2025-09-10 20:30:46',
                'deleted_at' => '2025-09-10 20:30:46',
            ],
            [
                'id' => 348,
                'color_name' => 'Chumbo/Arenito',
                'color_description' => 'Chumbo/Arenito',
                'color_code' => 'CHBARE',
                'product_id' => 29,
                'collection_id' => 11,
                'flag_product_id' => 1,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-10 20:16:59',
                'updated_at' => '2025-09-10 20:16:59',
                'deleted_at' => null,
            ],
            [
                'id' => 349,
                'color_name' => 'Arenito/Olympian',
                'color_description' => 'Arenito/Olympian',
                'color_code' => 'AREOLY',
                'product_id' => 29,
                'collection_id' => 11,
                'flag_product_id' => 1,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-10 20:16:59',
                'updated_at' => '2025-09-10 20:16:59',
                'deleted_at' => null,
            ],
            [
                'id' => 350,
                'color_name' => 'AREOLY',
                'color_description' => 'Arenito/Olympian',
                'color_code' => 'AREOLY',
                'product_id' => 27,
                'collection_id' => 11,
                'flag_product_id' => 1,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-10 20:17:53',
                'updated_at' => '2025-09-10 20:17:53',
                'deleted_at' => null,
            ],
            [
                'id' => 351,
                'color_name' => 'ARESOL',
                'color_description' => 'Arenito/Solar',
                'color_code' => 'ARESOL',
                'product_id' => 27,
                'collection_id' => 11,
                'flag_product_id' => 1,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-10 20:17:53',
                'updated_at' => '2025-09-10 20:17:53',
                'deleted_at' => null,
            ],
            [
                'id' => 352,
                'color_name' => 'RYLVRD',
                'color_description' => 'Royal/Verde',
                'color_code' => 'RYLVRD',
                'product_id' => 27,
                'collection_id' => 11,
                'flag_product_id' => 1,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-10 20:17:53',
                'updated_at' => '2025-09-10 20:17:53',
                'deleted_at' => null,
            ],
            [
                'id' => 353,
                'color_name' => 'Mescla/Stone',
                'color_description' => 'Mescla/Stone',
                'color_code' => 'MCSTON',
                'product_id' => 33,
                'collection_id' => 11,
                'flag_product_id' => 1,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-10 20:29:23',
                'updated_at' => '2025-09-10 20:29:23',
                'deleted_at' => null,
            ],
            [
                'id' => 354,
                'color_name' => 'Mescla/Preto/Preto',
                'color_description' => 'Mescla/Preto/Preto',
                'color_code' => 'MCPTPT',
                'product_id' => 33,
                'collection_id' => 11,
                'flag_product_id' => 1,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-10 20:29:23',
                'updated_at' => '2025-09-10 20:29:23',
                'deleted_at' => null,
            ],
            [
                'id' => 355,
                'color_name' => 'Mescla/Preto',
                'color_description' => 'Mescla/Preto',
                'color_code' => 'MC/PTO',
                'product_id' => 33,
                'collection_id' => 11,
                'flag_product_id' => 1,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-10 20:29:23',
                'updated_at' => '2025-09-10 20:29:23',
                'deleted_at' => null,
            ],
            [
                'id' => 356,
                'color_name' => 'Mescla/Vanguarda',
                'color_description' => 'Mescla/Vanguarda',
                'color_code' => 'MCVANG',
                'product_id' => 33,
                'collection_id' => 11,
                'flag_product_id' => 1,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-10 20:29:23',
                'updated_at' => '2025-09-10 20:29:23',
                'deleted_at' => null,
            ],
            [
                'id' => 357,
                'color_name' => 'Chumbo/Preto',
                'color_description' => 'Chumbo/Preto',
                'color_code' => 'CHB/PT',
                'product_id' => 31,
                'collection_id' => 11,
                'flag_product_id' => 3,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-10 20:30:39',
                'updated_at' => '2025-09-15 20:36:43',
                'deleted_at' => '2025-09-15 20:36:43',
            ],
            [
                'id' => 358,
                'color_name' => 'Elderme/Ameixa',
                'color_description' => 'Elderme/Ameixa',
                'color_code' => 'ELDAME',
                'product_id' => 31,
                'collection_id' => 11,
                'flag_product_id' => 3,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-10 20:30:39',
                'updated_at' => '2025-09-15 20:36:43',
                'deleted_at' => '2025-09-15 20:36:43',
            ],
            [
                'id' => 359,
                'color_name' => 'Preto/Preto',
                'color_description' => 'Preto/Preto',
                'color_code' => 'PTO/PT',
                'product_id' => 31,
                'collection_id' => 11,
                'flag_product_id' => 3,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-10 20:30:39',
                'updated_at' => '2025-09-15 20:36:43',
                'deleted_at' => '2025-09-15 20:36:43',
            ],
            [
                'id' => 360,
                'color_name' => 'Algodão/Dusty',
                'color_description' => 'Algodão/Dusty',
                'color_code' => 'ALGDST',
                'product_id' => 31,
                'collection_id' => 11,
                'flag_product_id' => 3,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-10 20:30:39',
                'updated_at' => '2025-09-15 20:36:43',
                'deleted_at' => '2025-09-15 20:36:43',
            ],
            [
                'id' => 361,
                'color_name' => 'Cinza/Steel',
                'color_description' => 'Cinza/Steel',
                'color_code' => 'CZASTE',
                'product_id' => 31,
                'collection_id' => 11,
                'flag_product_id' => 3,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-10 20:30:39',
                'updated_at' => '2025-09-15 20:36:43',
                'deleted_at' => '2025-09-15 20:36:43',
            ],
            [
                'id' => 362,
                'color_name' => 'Arenito/Marfim',
                'color_description' => 'Arenito/Marfim',
                'color_code' => 'ARTMRF',
                'product_id' => 31,
                'collection_id' => 11,
                'flag_product_id' => 3,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-10 20:30:39',
                'updated_at' => '2025-09-15 20:36:43',
                'deleted_at' => '2025-09-15 20:36:43',
            ],
            [
                'id' => 363,
                'color_name' => 'Chumbo/Verde',
                'color_description' => 'Chumbo/Verde',
                'color_code' => 'CHB/VD',
                'product_id' => 32,
                'collection_id' => 11,
                'flag_product_id' => 1,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-10 20:30:46',
                'updated_at' => '2025-09-18 16:37:33',
                'deleted_at' => '2025-09-18 16:37:33',
            ],
            [
                'id' => 364,
                'color_name' => 'Preto/Preto',
                'color_description' => 'Preto/Preto',
                'color_code' => 'PTO/PT',
                'product_id' => 32,
                'collection_id' => 11,
                'flag_product_id' => 1,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-10 20:30:46',
                'updated_at' => '2025-09-18 16:37:33',
                'deleted_at' => '2025-09-18 16:37:33',
            ],
            [
                'id' => 365,
                'color_name' => 'Marinho/Dourado',
                'color_description' => 'Marinho/Dourado',
                'color_code' => 'MRHDRD',
                'product_id' => 32,
                'collection_id' => 11,
                'flag_product_id' => 1,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-10 20:30:46',
                'updated_at' => '2025-09-18 16:37:33',
                'deleted_at' => '2025-09-18 16:37:33',
            ],
            [
                'id' => 366,
                'color_name' => 'Arenito/Chumbo',
                'color_description' => 'Arenito/Chumbo',
                'color_code' => 'ARECHB',
                'product_id' => 32,
                'collection_id' => 11,
                'flag_product_id' => 1,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-10 20:30:46',
                'updated_at' => '2025-09-18 16:37:33',
                'deleted_at' => '2025-09-18 16:37:33',
            ],
            [
                'id' => 367,
                'color_name' => 'Preto/Preto',
                'color_description' => 'Preto/Preto',
                'color_code' => 'PTO/PT',
                'product_id' => 34,
                'collection_id' => 11,
                'flag_product_id' => 1,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-10 20:35:10',
                'updated_at' => '2025-09-10 20:35:21',
                'deleted_at' => '2025-09-10 20:35:21',
            ],
            [
                'id' => 368,
                'color_name' => 'Preto/Preto',
                'color_description' => 'Preto/Preto',
                'color_code' => 'PTO/PT',
                'product_id' => 34,
                'collection_id' => 11,
                'flag_product_id' => 1,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-10 20:35:21',
                'updated_at' => '2025-09-10 20:39:53',
                'deleted_at' => '2025-09-10 20:39:53',
            ],
            [
                'id' => 369,
                'color_name' => 'Chumbo/Organza',
                'color_description' => 'Chumbo/Organza',
                'color_code' => 'CHBORG',
                'product_id' => 35,
                'collection_id' => 11,
                'flag_product_id' => 1,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-10 20:39:28',
                'updated_at' => '2025-09-10 20:39:28',
                'deleted_at' => null,
            ],
            [
                'id' => 370,
                'color_name' => 'Marinho/Cristal',
                'color_description' => 'Marinho/Cristal',
                'color_code' => 'MRHCRS',
                'product_id' => 35,
                'collection_id' => 11,
                'flag_product_id' => 1,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-10 20:39:28',
                'updated_at' => '2025-09-10 20:39:28',
                'deleted_at' => null,
            ],
            [
                'id' => 371,
                'color_name' => 'Arenito',
                'color_description' => 'Arenito',
                'color_code' => 'ARENIT',
                'product_id' => 35,
                'collection_id' => 11,
                'flag_product_id' => 1,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-10 20:39:28',
                'updated_at' => '2025-09-10 20:39:28',
                'deleted_at' => null,
            ],
            [
                'id' => 372,
                'color_name' => 'Preto',
                'color_description' => 'Preto',
                'color_code' => 'PRETO',
                'product_id' => 35,
                'collection_id' => 11,
                'flag_product_id' => 1,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-10 20:39:28',
                'updated_at' => '2025-09-10 20:39:28',
                'deleted_at' => null,
            ],
            [
                'id' => 373,
                'color_name' => 'Preto/Preto',
                'color_description' => 'Preto/Preto',
                'color_code' => 'PTO/PT',
                'product_id' => 34,
                'collection_id' => 11,
                'flag_product_id' => 1,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-10 20:39:53',
                'updated_at' => '2025-09-10 20:39:53',
                'deleted_at' => null,
            ],
            [
                'id' => 374,
                'color_name' => 'Preto/Chumbo',
                'color_description' => 'Preto/Chumbo',
                'color_code' => 'PTO/CH',
                'product_id' => 36,
                'collection_id' => 11,
                'flag_product_id' => 1,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-10 20:47:26',
                'updated_at' => '2025-09-10 20:47:26',
                'deleted_at' => null,
            ],
            [
                'id' => 375,
                'color_name' => 'Preto/Preto',
                'color_description' => 'Preto/Preto',
                'color_code' => 'PTO/PT',
                'product_id' => 36,
                'collection_id' => 11,
                'flag_product_id' => 1,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-10 20:47:26',
                'updated_at' => '2025-09-10 20:47:26',
                'deleted_at' => null,
            ],
            [
                'id' => 376,
                'color_name' => 'Chumbo/Preto',
                'color_description' => 'Chumbo/Preto',
                'color_code' => 'CHB/PT',
                'product_id' => 36,
                'collection_id' => 11,
                'flag_product_id' => 1,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-10 20:47:26',
                'updated_at' => '2025-09-10 20:47:26',
                'deleted_at' => null,
            ],
            [
                'id' => 377,
                'color_name' => 'Preto',
                'color_description' => 'Preto',
                'color_code' => 'PRETO',
                'product_id' => 37,
                'collection_id' => 11,
                'flag_product_id' => 1,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-10 20:53:40',
                'updated_at' => '2025-09-18 22:54:02',
                'deleted_at' => '2025-09-18 22:54:02',
            ],
            [
                'id' => 378,
                'color_name' => 'Azul Claro',
                'color_description' => 'Azul Claro',
                'color_code' => 'AZL/CL',
                'product_id' => 37,
                'collection_id' => 11,
                'flag_product_id' => 1,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-10 20:53:40',
                'updated_at' => '2025-09-18 22:54:02',
                'deleted_at' => '2025-09-18 22:54:02',
            ],
            [
                'id' => 379,
                'color_name' => 'Verde Militar',
                'color_description' => 'Verde Militar',
                'color_code' => 'VDEMLT',
                'product_id' => 37,
                'collection_id' => 11,
                'flag_product_id' => 1,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-10 20:53:40',
                'updated_at' => '2025-09-18 22:54:02',
                'deleted_at' => '2025-09-18 22:54:02',
            ],
            [
                'id' => 380,
                'color_name' => 'Preto/Madeira',
                'color_description' => 'Preto/Madeira',
                'color_code' => 'PTOMAD',
                'product_id' => 37,
                'collection_id' => 11,
                'flag_product_id' => 1,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-10 20:53:40',
                'updated_at' => '2025-09-18 22:54:02',
                'deleted_at' => '2025-09-18 22:54:02',
            ],
            [
                'id' => 381,
                'color_name' => 'Areniti/Marrom',
                'color_description' => 'Areniti/Marrom',
                'color_code' => 'AREMRO',
                'product_id' => 37,
                'collection_id' => 11,
                'flag_product_id' => 1,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-10 20:53:40',
                'updated_at' => '2025-09-18 22:54:02',
                'deleted_at' => '2025-09-18 22:54:02',
            ],
            [
                'id' => 382,
                'color_name' => 'Whisky',
                'color_description' => 'Whisky',
                'color_code' => 'WHISKY',
                'product_id' => 38,
                'collection_id' => 11,
                'flag_product_id' => 4,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-10 21:00:26',
                'updated_at' => '2025-09-16 20:00:25',
                'deleted_at' => '2025-09-16 20:00:25',
            ],
            [
                'id' => 383,
                'color_name' => 'Chumbo/Preto',
                'color_description' => 'Chumbo/Preto',
                'color_code' => 'CHB/PT',
                'product_id' => 31,
                'collection_id' => 11,
                'flag_product_id' => 3,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-15 20:36:43',
                'updated_at' => '2025-09-18 16:36:40',
                'deleted_at' => '2025-09-18 16:36:40',
            ],
            [
                'id' => 384,
                'color_name' => 'Elderme/Ameixa',
                'color_description' => 'Elderme/Ameixa',
                'color_code' => 'ELDAME',
                'product_id' => 31,
                'collection_id' => 11,
                'flag_product_id' => 3,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-15 20:36:43',
                'updated_at' => '2025-09-18 16:36:40',
                'deleted_at' => '2025-09-18 16:36:40',
            ],
            [
                'id' => 385,
                'color_name' => 'Preto/Preto',
                'color_description' => 'Preto/Preto',
                'color_code' => 'PTO/PT',
                'product_id' => 31,
                'collection_id' => 11,
                'flag_product_id' => 3,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-15 20:36:43',
                'updated_at' => '2025-09-18 16:36:40',
                'deleted_at' => '2025-09-18 16:36:40',
            ],
            [
                'id' => 386,
                'color_name' => 'Algodão/Dusty',
                'color_description' => 'Algodão/Dusty',
                'color_code' => 'ALGDST',
                'product_id' => 31,
                'collection_id' => 11,
                'flag_product_id' => 3,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-15 20:36:43',
                'updated_at' => '2025-09-18 16:36:40',
                'deleted_at' => '2025-09-18 16:36:40',
            ],
            [
                'id' => 387,
                'color_name' => 'Cinza/Steel',
                'color_description' => 'Cinza/Steel',
                'color_code' => 'CZASTE',
                'product_id' => 31,
                'collection_id' => 11,
                'flag_product_id' => 3,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-15 20:36:43',
                'updated_at' => '2025-09-18 16:36:40',
                'deleted_at' => '2025-09-18 16:36:40',
            ],
            [
                'id' => 388,
                'color_name' => 'Arenito/Marfim',
                'color_description' => 'Arenito/Marfim',
                'color_code' => 'ARTMRF',
                'product_id' => 31,
                'collection_id' => 11,
                'flag_product_id' => 3,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-15 20:36:43',
                'updated_at' => '2025-09-18 16:36:40',
                'deleted_at' => '2025-09-18 16:36:40',
            ],
            [
                'id' => 389,
                'color_name' => 'Whisky',
                'color_description' => 'Whisky',
                'color_code' => 'WHISKY',
                'product_id' => 38,
                'collection_id' => 11,
                'flag_product_id' => 4,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-16 20:00:25',
                'updated_at' => '2025-09-16 20:01:18',
                'deleted_at' => '2025-09-16 20:01:18',
            ],
            [
                'id' => 390,
                'color_name' => 'Whisky',
                'color_description' => 'Whisky',
                'color_code' => 'WHISKY',
                'product_id' => 38,
                'collection_id' => 11,
                'flag_product_id' => 4,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-16 20:01:18',
                'updated_at' => '2025-09-16 21:36:03',
                'deleted_at' => '2025-09-16 21:36:03',
            ],
            [
                'id' => 391,
                'color_name' => 'Whisky',
                'color_description' => 'Whisky',
                'color_code' => 'WHISKY',
                'product_id' => 38,
                'collection_id' => 11,
                'flag_product_id' => 4,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-16 21:36:03',
                'updated_at' => '2025-09-17 17:50:42',
                'deleted_at' => '2025-09-17 17:50:42',
            ],
            [
                'id' => 392,
                'color_name' => 'Whisky',
                'color_description' => 'Whisky',
                'color_code' => 'WHISKY',
                'product_id' => 38,
                'collection_id' => 11,
                'flag_product_id' => 4,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-17 17:50:42',
                'updated_at' => '2025-09-18 22:53:31',
                'deleted_at' => '2025-09-18 22:53:31',
            ],
            [
                'id' => 393,
                'color_name' => 'Preto/Chumbo',
                'color_description' => 'Preto/Chumbo',
                'color_code' => 'PTO/CH',
                'product_id' => 30,
                'collection_id' => 11,
                'flag_product_id' => 1,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-18 16:29:33',
                'updated_at' => '2025-09-19 18:50:27',
                'deleted_at' => '2025-09-19 18:50:27',
            ],
            [
                'id' => 394,
                'color_name' => 'Militar/Preto',
                'color_description' => 'Militar/Preto',
                'color_code' => 'MLT/PT',
                'product_id' => 30,
                'collection_id' => 11,
                'flag_product_id' => 1,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-18 16:29:33',
                'updated_at' => '2025-09-19 18:50:27',
                'deleted_at' => '2025-09-19 18:50:27',
            ],
            [
                'id' => 395,
                'color_name' => 'Branco/Preto',
                'color_description' => 'Branco/Preto',
                'color_code' => 'BCOPTO',
                'product_id' => 30,
                'collection_id' => 11,
                'flag_product_id' => 1,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-18 16:29:33',
                'updated_at' => '2025-09-19 18:50:27',
                'deleted_at' => '2025-09-19 18:50:27',
            ],
            [
                'id' => 396,
                'color_name' => 'Arenito/Lilas',
                'color_description' => 'Arenito/Lilas',
                'color_code' => 'ARELLS',
                'product_id' => 30,
                'collection_id' => 11,
                'flag_product_id' => 1,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-18 16:29:33',
                'updated_at' => '2025-09-19 18:50:27',
                'deleted_at' => '2025-09-19 18:50:27',
            ],
            [
                'id' => 397,
                'color_name' => 'Chumbo/Preto',
                'color_description' => 'Chumbo/Preto',
                'color_code' => 'CHB/PT',
                'product_id' => 31,
                'collection_id' => 11,
                'flag_product_id' => 3,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-18 16:36:40',
                'updated_at' => '2025-09-18 16:36:40',
                'deleted_at' => null,
            ],
            [
                'id' => 398,
                'color_name' => 'Elderme/Ameixa',
                'color_description' => 'Elderme/Ameixa',
                'color_code' => 'ELDAME',
                'product_id' => 31,
                'collection_id' => 11,
                'flag_product_id' => 3,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-18 16:36:40',
                'updated_at' => '2025-09-18 16:36:40',
                'deleted_at' => null,
            ],
            [
                'id' => 399,
                'color_name' => 'Preto/Preto',
                'color_description' => 'Preto/Preto',
                'color_code' => 'PTO/PT',
                'product_id' => 31,
                'collection_id' => 11,
                'flag_product_id' => 3,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-18 16:36:40',
                'updated_at' => '2025-09-18 16:36:40',
                'deleted_at' => null,
            ],
            [
                'id' => 400,
                'color_name' => 'Algodão/Dusty',
                'color_description' => 'Algodão/Dusty',
                'color_code' => 'ALGDST',
                'product_id' => 31,
                'collection_id' => 11,
                'flag_product_id' => 3,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-18 16:36:40',
                'updated_at' => '2025-09-18 16:36:40',
                'deleted_at' => null,
            ],
            [
                'id' => 401,
                'color_name' => 'Cinza/Steel',
                'color_description' => 'Cinza/Steel',
                'color_code' => 'CZASTE',
                'product_id' => 31,
                'collection_id' => 11,
                'flag_product_id' => 3,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-18 16:36:40',
                'updated_at' => '2025-09-18 16:36:40',
                'deleted_at' => null,
            ],
            [
                'id' => 402,
                'color_name' => 'Arenito/Marfim',
                'color_description' => 'Arenito/Marfim',
                'color_code' => 'ARTMRF',
                'product_id' => 31,
                'collection_id' => 11,
                'flag_product_id' => 3,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-18 16:36:40',
                'updated_at' => '2025-09-18 16:36:40',
                'deleted_at' => null,
            ],
            [
                'id' => 403,
                'color_name' => 'Chumbo/Verde',
                'color_description' => 'Chumbo/Verde',
                'color_code' => 'CHB/VD',
                'product_id' => 32,
                'collection_id' => 11,
                'flag_product_id' => 1,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-18 16:37:33',
                'updated_at' => '2025-09-18 16:51:47',
                'deleted_at' => '2025-09-18 16:51:47',
            ],
            [
                'id' => 404,
                'color_name' => 'Preto/Preto',
                'color_description' => 'Preto/Preto',
                'color_code' => 'PTO/PT',
                'product_id' => 32,
                'collection_id' => 11,
                'flag_product_id' => 1,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-18 16:37:33',
                'updated_at' => '2025-09-18 16:51:47',
                'deleted_at' => '2025-09-18 16:51:47',
            ],
            [
                'id' => 405,
                'color_name' => 'Marinho/Dourado',
                'color_description' => 'Marinho/Dourado',
                'color_code' => 'MRHDRD',
                'product_id' => 32,
                'collection_id' => 11,
                'flag_product_id' => 1,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-18 16:37:33',
                'updated_at' => '2025-09-18 16:51:47',
                'deleted_at' => '2025-09-18 16:51:47',
            ],
            [
                'id' => 406,
                'color_name' => 'Arenito/Chumbo',
                'color_description' => 'Arenito/Chumbo',
                'color_code' => 'ARECHB',
                'product_id' => 32,
                'collection_id' => 11,
                'flag_product_id' => 1,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-18 16:37:33',
                'updated_at' => '2025-09-18 16:51:47',
                'deleted_at' => '2025-09-18 16:51:47',
            ],
            [
                'id' => 407,
                'color_name' => 'Chumbo/Verde',
                'color_description' => 'Chumbo/Verde',
                'color_code' => 'CHB/VD',
                'product_id' => 32,
                'collection_id' => 11,
                'flag_product_id' => 1,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-18 16:51:47',
                'updated_at' => '2025-09-18 16:51:47',
                'deleted_at' => null,
            ],
            [
                'id' => 408,
                'color_name' => 'Preto/Preto',
                'color_description' => 'Preto/Preto',
                'color_code' => 'PTO/PT',
                'product_id' => 32,
                'collection_id' => 11,
                'flag_product_id' => 1,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-18 16:51:47',
                'updated_at' => '2025-09-18 16:51:47',
                'deleted_at' => null,
            ],
            [
                'id' => 409,
                'color_name' => 'Marinho/Dourado',
                'color_description' => 'Marinho/Dourado',
                'color_code' => 'MRHDRD',
                'product_id' => 32,
                'collection_id' => 11,
                'flag_product_id' => 1,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-18 16:51:47',
                'updated_at' => '2025-09-18 16:51:47',
                'deleted_at' => null,
            ],
            [
                'id' => 410,
                'color_name' => 'Arenito/Chumbo',
                'color_description' => 'Arenito/Chumbo',
                'color_code' => 'ARECHB',
                'product_id' => 32,
                'collection_id' => 11,
                'flag_product_id' => 1,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-18 16:51:47',
                'updated_at' => '2025-09-18 16:51:47',
                'deleted_at' => null,
            ],
            [
                'id' => 411,
                'color_name' => 'Whisky',
                'color_description' => 'Whisky',
                'color_code' => 'WHISKY',
                'product_id' => 38,
                'collection_id' => 11,
                'flag_product_id' => 4,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-18 22:53:31',
                'updated_at' => '2025-09-18 22:53:31',
                'deleted_at' => null,
            ],
            [
                'id' => 412,
                'color_name' => 'Preto',
                'color_description' => 'Preto',
                'color_code' => 'PRETO',
                'product_id' => 37,
                'collection_id' => 11,
                'flag_product_id' => 1,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-18 22:54:02',
                'updated_at' => '2025-09-18 22:54:02',
                'deleted_at' => null,
            ],
            [
                'id' => 413,
                'color_name' => 'Azul Claro',
                'color_description' => 'Azul Claro',
                'color_code' => 'AZL/CL',
                'product_id' => 37,
                'collection_id' => 11,
                'flag_product_id' => 1,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-18 22:54:02',
                'updated_at' => '2025-09-18 22:54:02',
                'deleted_at' => null,
            ],
            [
                'id' => 414,
                'color_name' => 'Verde Militar',
                'color_description' => 'Verde Militar',
                'color_code' => 'VDEMLT',
                'product_id' => 37,
                'collection_id' => 11,
                'flag_product_id' => 1,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-18 22:54:02',
                'updated_at' => '2025-09-18 22:54:02',
                'deleted_at' => null,
            ],
            [
                'id' => 415,
                'color_name' => 'Preto/Madeira',
                'color_description' => 'Preto/Madeira',
                'color_code' => 'PTOMAD',
                'product_id' => 37,
                'collection_id' => 11,
                'flag_product_id' => 1,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-18 22:54:02',
                'updated_at' => '2025-09-18 22:54:02',
                'deleted_at' => null,
            ],
            [
                'id' => 416,
                'color_name' => 'Areniti/Marrom',
                'color_description' => 'Areniti/Marrom',
                'color_code' => 'AREMRO',
                'product_id' => 37,
                'collection_id' => 11,
                'flag_product_id' => 1,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-18 22:54:02',
                'updated_at' => '2025-09-18 22:54:02',
                'deleted_at' => null,
            ],
            [
                'id' => 417,
                'color_name' => 'Preto/Chumbo',
                'color_description' => 'Preto/Chumbo',
                'color_code' => 'PTO/CH',
                'product_id' => 30,
                'collection_id' => 11,
                'flag_product_id' => 1,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-19 18:50:27',
                'updated_at' => '2025-09-19 18:50:27',
                'deleted_at' => null,
            ],
            [
                'id' => 418,
                'color_name' => 'Militar/Preto',
                'color_description' => 'Militar/Preto',
                'color_code' => 'MLT/PT',
                'product_id' => 30,
                'collection_id' => 11,
                'flag_product_id' => 1,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-19 18:50:27',
                'updated_at' => '2025-09-19 18:50:27',
                'deleted_at' => null,
            ],
            [
                'id' => 419,
                'color_name' => 'Branco/Preto',
                'color_description' => 'Branco/Preto',
                'color_code' => 'BCOPTO',
                'product_id' => 30,
                'collection_id' => 11,
                'flag_product_id' => 1,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-19 18:50:27',
                'updated_at' => '2025-09-19 18:50:27',
                'deleted_at' => null,
            ],
            [
                'id' => 420,
                'color_name' => 'Arenito/Lilas',
                'color_description' => 'Arenito/Lilas',
                'color_code' => 'ARELLS',
                'product_id' => 30,
                'collection_id' => 11,
                'flag_product_id' => 1,
                'is_new' => 0,
                'active' => 1,
                'created_at' => '2025-09-19 18:50:27',
                'updated_at' => '2025-09-19 18:50:27',
                'deleted_at' => null,
            ],
        ]);
        
        // Re-enable foreign key checks
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
        
        $this->command->info('ColorsTableSeeder completed successfully.');
    }
}